# 修复等级
preset: laravel

# 是否启用危险的修复
risky: false

finder:
    path: 
        - "bootstrap"
        - "config"
        - "database"
        - "phpwind9"
        - "public"
        - "routes"
        - "src"
